#This is a homework file for an example, blah blah blah
print("hjkgdsajhfgksadgfhasdgfhaskdfghwkdsgfhasdgfdksghfhajksdgfhsagfkasdjhfgsakfhjgasgfkjhasgfjhsakgfhjaskgfhjasjfgkasjhdfgkasjhfgskaj")
print("Do you like to read jdskafjashdgfkjahdsfgjksdfaghfdsgkafdsgjhadsdfkjfghshagsdfjfgjh")